import { existsSync, mkdirSync, writeFileSync } from "node:fs"
import path from "node:path"
import { loadConfig } from "../../config/load-config"
import { scanRoutes } from "../../scanner/scan-routes"
import { resolvePath } from "../../utils/path"
import { initUiSettings, areColorsEnabled } from "../ui/terminal"
import { colors } from "../ui/colors"
import { symbols } from "../ui/symbols"
import { formatHeader } from "../ui/format"
import { getActionNames } from "../ui/table"

export async function typegenCommand(
  root: string,
  options: {
    plain?: boolean | undefined
    noColor?: boolean | undefined
  } = {}
): Promise<void> {
  initUiSettings({ plain: options.plain, noColor: options.noColor })

  const isPlain = !areColorsEnabled()
  const config = await loadConfig(root)
  const routesDir = resolvePath(root, config.app.routesDir)

  const pageTypes: string[] = []
  const apiTypes: string[] = []
  const actionTypes: string[] = []

  if (existsSync(routesDir)) {
    const routes = scanRoutes(routesDir)
    
    const pageItems = routes.filter(item => item.kind === "page")
    const apiItems = routes.filter(item => item.kind === "api")

    for (const item of pageItems) {
      pageTypes.push(routePathToTypeScriptType(item.routePath))
      if (item.actionsModule) {
        const actions = getActionNames(item.actionsModule)
        for (const act of actions) {
          actionTypes.push(routePathToTypeScriptType(`${item.routePath}?/${act}`))
        }
      }
    }

    for (const item of apiItems) {
      const apiPath = item.apiPath ?? item.routePath
      apiTypes.push(routePathToTypeScriptType(apiPath))
    }
  }

  // Generate .d.ts content
  const content = `// Generated by Kumquat typegen. Do not edit.

export type PageRoute =
  ${pageTypes.map(t => `| ${t}`).join("\n  ") || "| string"}

export type ApiRoute =
  ${apiTypes.map(t => `| ${t}`).join("\n  ") || "| string"}

export type ActionRoute =
  ${actionTypes.map(t => `| ${t}`).join("\n  ") || "| string"}
`

  const outDir = path.join(root, ".kumquat", "types")
  mkdirSync(outDir, { recursive: true })
  
  const outFile = path.join(outDir, "routes.d.ts")
  writeFileSync(outFile, content, "utf8")

  const displayOut = path.relative(root, outFile)

  console.log(formatHeader("typegen", isPlain))
  console.log("")

  if (isPlain) {
    console.log(`output ${displayOut}`)
    console.log("")
    console.log("generated route types")
  } else {
    console.log(`  ${colors.muted("output")} ${colors.bold(displayOut)}`)
    console.log("")
    console.log(`${colors.success(symbols.success())} ${colors.bold("generated route types")}`)
  }
}

function routePathToTypeScriptType(pathStr: string): string {
  const parts = pathStr.split("?")
  const routePart = parts[0] ?? ""
  const queryPart = parts[1]
  const segments = routePart.split("/")
  const convertedSegments = segments.map(seg => {
    if (seg.startsWith(":") || seg.startsWith("*")) {
      return "${string}"
    }
    return seg
  })
  const convertedRoute = convertedSegments.join("/")
  
  if (queryPart) {
    if (pathStr.includes(":") || pathStr.includes("*")) {
      return `\`${convertedRoute}?/${queryPart.replace(/^\//, "")}\``
    } else {
      return `"${convertedRoute}?/${queryPart.replace(/^\//, "")}"`
    }
  }
  
  if (pathStr.includes(":") || pathStr.includes("*")) {
    return `\`${convertedRoute}\``
  }
  return `"${convertedRoute}"`
}
